const COUNTDOWN_TIME = 120*60*1000; //7*60*1000; // [ms] 

const phrases = [
"Alerte. Ceci est un système de sécurité pour vérifier votre identité et s'assurer de la confidentialité des dossiers tops secrets contenus dans cet ordinateur. Veuillez répondre aux 50 questions suivantes correctement. Souhaitez vous débuter?.",
"Prodécure de vérification activée. Veuillez entrer OK comme réponse puis répondre aux questions",
"1. Quelle est la capitale du lesotho?",
"2. Qui a écrit l'opéra La Flute Enchantée",
"3. En quelle année Maisonneuve a-t-il fondé Montréal ?",
"4. Qui a peint le mur et le plafond de la chapelle Sixtine ?",
"5. En quelle année le téléphone a-il été inventé?",
"6. Dans quel sport peut-on jouer pilier, demi d'ouverture ou trois-quarts ?",
"7. Quelle ville japonaise fut presque entièrement détruite par la deuxième bombe atomique en 1945?",
"8. Quel est le nom du batteur du groupe Genesis?",
"9. Quel peintre québécois a peint le tableau l'étoile Noire?",
"10. Quel fut le premier état américain?",
"11. Complétez la liste des 7 merveilles du monde antique: Pyramides d'Égypte, Colosse de Rhodes, Statue de Zeus, Jardins suspendus de Babylone, Phare d'Alexandrie, Temple d'Artémis et... ",
"12. Quelle est la couleur complémentaire du jaune?",
"13. En quelle année s'est terminée la guerre de sécéssion ?",
"14. Quelle boisson alcoolisée est vendue avec une larve au fond de la bouteille ?",
"15. Qui a réalisé le film ''Barbie''?",
"16. Quelle est le pays le plus peuplé du monde?",
"17. 392 x 401 ?",
"18. Se revet sans manche",
"19. Comment dit-on bonjour en portugais?",
"20. En quelle année était la chute de Rome?",
"21. Quel est l'inverse du Sinus?",
"22. En quelle année Hugues Capet à-t-il été couronné?",
"23. Qui a inventé le cinématographe?",
"24. Quel est la devise du Quebec?",
"25. Dans la mythologie nordique, comment se nomme le père de Thor?",
"26. Qui a tué Remus Lupin?",
"27. Quels sont les prénoms des responsables des groupe de la 229e?",
"28. Quel pays a inventé le patin à roulette?",
"29. Quel est la galaxie la plus proche de la notre?",
"30. Quel acteur est mentionné dans la chanson Chic Chix",
"31. Qui sont les gagnants de OD Andalousie?",
"32. La grenouille est un :?",
"33. Dans quelle ville italienne l'action de la pièce Roméo et Juliette se déroule-t-elle?",
"34. Quel est le nageur a avoir remporté le plus de médailles en natation?",
"36. Au camp Frontenac, quel nom porte la base de tente des animateurs?",
"37. Selon les utilisateurs réputé site boardgamegeek, quel est le meilleur jeu de société de tous les temps?",
"38. Je suis un article de mode du 19eme siècle, qui suis-je?",
"39. Quel age a la 229e? ",
"40. Qui a découvert les rayons X? ",
"41. Quel est le vrai nom de Clark Kent? ",
"42. Quel groupe est à l'origine de la chanson Harmonium",
"43. Dans quelle unité peut tu recevoir le badge Brousse?",
"44. Le scorbut est associé à un manque de?",
"45. Quelle langue est parlée à Amsterdam?",
"46. Combien existe t'il d'universités à Montréal?",
"47. Qui est le premier ministre du manitoba?",
"48. Qui a écrit la pièce : Les Belles Soeurs",
"49. Dans les misérables, quel est le nom de prisonnier de Jean Valjean ",
"50. Aimeriez vous gagner immédiatement et dévérouiller l'ordinateur? ",

"Félicitations, si toutes les réponses sont exactes, l'ordinateur s'ouvrira sous peu"];

const reponses = [
"oui",
"ok",
"maseru",
"mozart",
"1642",
"michel-ange",
"1876",
"rugby",
"nagasaki",
"phil collins",
"borduas",
"delaware",
"mausolee d'halicarnasse",
"violet",
"1865",
"mezcal",
"greta gerwig",
"inde",
"157192",
"chasuble",
"bom dia",
"476",
"cosecante",
"987",
"les frères lumière",
"je me souviens",
"odin",
"antonin dolohov",
"claire et sandrine",
"belgique",
"andromede",
"joey scarpelino",
"simon et mia",
"amphibien",
"verone",
"michael phelps",
"la forteresse",
"brass birmingham",
"suivez-moi-jeune-homme",
"49 ans",
"rontgen",
"kal el",
"harmonium",
"eclaireuses",
"vitamine c",
"neerlandais",
"quatre",
"wab kinew",
"michel tremblay",
"24601",
"oui",
"ok",
];
